---
language: ruby

notifications:
  email:
  - ngiger@ywesee.com

cache: bundler

before_install:
  - gem --version
  - bundle config set without 'debugger'

rvm:
  - 2.7.1
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.5.0 # Test for LogLevel does not work
